import {asset,writeJSON} from '../.agents/skills/cloudflare-cost-safety/scripts/lib/core.mjs';
const string={type:'string',minLength:1}, sha={type:'string',pattern:'^[a-f0-9]{64}$'},nullableSha={anyOf:[sha,{type:'null'}]},status={enum:['PASS','BLOCK','INCOMPLETE','REVIEW']};
const ruleId={enum:['CF-DO-001','CF-DO-002','CF-DEP-001','CF-SQL-001','CF-SQL-002','CF-JOB-001','CF-Q-001','CF-Q-002','CF-KV-001','CF-R2-001','CF-HTTP-001','CF-SAFE-001']};
const dimensions=['events','queue_deliveries','new_messages','sql_rows_read','sql_rows_written','kv_reads','kv_writes','kv_lists','r2_class_a','r2_class_b','active_objects','environments'];
function object(required,properties,additionalProperties=false){return {type:'object',required,properties,additionalProperties};}
function schema(name,definition){writeJSON(asset(`${name}.schema.json`),{$schema:'http://json-schema.org/draft-07/schema#',$id:`https://cloudflare-cost-safety.local/schema/${name}`, ...definition});}
const location=object(['path','start_line'],{path:string,start_line:{type:'integer',minimum:1},end_line:{type:'integer',minimum:1}},false);
const count={type:'integer',minimum:0,maximum:Number.MAX_SAFE_INTEGER};
const work={type:'object',minProperties:1,additionalProperties:count};
schema('execution-bounds',object(['paths'],{paths:{type:'array',minItems:1,items:{
 ...object(['path_id','scope','max_events','work_limits','reason','enforcement','observations'],{
  path_id:string,scope:{enum:['invocation','logical_job','time_window']},max_events:{...count,minimum:1},window_ms:{...count,minimum:1},work_limits:work,reason:string,
  enforcement:{type:'array',minItems:1,items:location},
  observations:{type:'array',minItems:1,items:object(['scenario','case','events','work'],{scenario:{enum:['normal','no_progress','amplification','exhaustion','restart','replay','stop','time_boundary','partial_failure']},case:string,events:count,work})}
 }),allOf:[{if:{properties:{scope:{const:'time_window'}}},then:{required:['window_ms']}}]
}}}));
schema('policy',object(['schema_version','mode','cloud_access','remote_tests','local_test_budget'],{
 schema_version:{const:'1.0'},mode:{const:'review_only'},cloud_access:{const:'disabled'},remote_tests:{const:false},
 local_test_budget:object(['max_events','max_messages','max_fixture_rows','max_wall_seconds_per_child','max_memory_mb','network'],{max_events:{type:'integer',minimum:1,maximum:1000},max_messages:{type:'integer',minimum:1,maximum:1000},max_fixture_rows:{type:'integer',minimum:1,maximum:10000},max_wall_seconds_per_child:{type:'integer',minimum:1,maximum:60},max_memory_mb:{type:'integer',minimum:64,maximum:1024},network:{const:'deny'}},false),
 money_budget:object(['monthly_usd','status'],{monthly_usd:{type:'number',minimum:0},status:{const:'declared_not_enforced'},plan:string,billing_period:string},false),
 enforcement_evidence:{type:'array',items:location},required_tests:{type:'array',uniqueItems:true,items:string},exemptions:{type:'array',maxItems:0},max_evidence_age_hours:{type:'integer',minimum:1,maximum:168}
}));
schema('deployment-identity',object(['schema_version','source_snapshot_digest','artifact_digest','artifact_path','effective_config_digest','config_path','target','official_skills_lock_digest','policy_digest','rules_digest','tool_digest','toolchain','migration_digest','digest'],{
 schema_version:{const:'1.0'},source_snapshot_digest:sha,commit:{type:['string','null']},artifact_digest:nullableSha,artifact_path:{type:['string','null']},effective_config_digest:nullableSha,config_path:{type:['string','null']},
 target:object(['account_id','application','environment','action'],{account_id:{type:['string','null']},application:{type:['string','null']},environment:string,action:{enum:['deploy','preview','promote','rollback','upload','secret_deploy']},candidate_version:{type:['string','null']}}),
 official_skills_lock_digest:nullableSha,policy_digest:sha,rules_digest:sha,tool_digest:sha,toolchain:{type:'object'},migration_digest:sha,builder:string,digest:sha
}));
schema('official-skills-lock',object(['schema_version','upstream','revision','license','license_verified','license_sha256','prepared_at','skills'],{
 schema_version:{const:'1.0'},upstream:{const:'https://github.com/cloudflare/skills'},revision:{type:'string',pattern:'^[a-f0-9]{40}$'},license:{const:'Apache-2.0'},license_verified:{const:true},license_sha256:sha,prepared_at:string,
 skills:{type:'array',minItems:3,items:object(['name','upstream_path','resolved_local_path','files','content_tree_sha256'],{name:{enum:['workers-best-practices','wrangler','durable-objects']},upstream_path:string,resolved_local_path:string,files:{type:'object',minProperties:1,additionalProperties:sha},content_tree_sha256:sha})}
}));
const finding=object(['id','rule_id','origin','status','severity','confidence','location','summary','execution_path','usage_assessment','evidence'],{id:string,rule_id:{type:['string','null']},origin:{enum:['official_best_practices','cost_safety','both']},status:{enum:['BLOCK','REVIEW','ADVISORY']},severity:{enum:['critical','high','medium','low','info']},confidence:string,location,summary:string,execution_path:{type:'array',items:string},usage_assessment:{type:'object'},native_control_limit:{type:['string','null']},recommendation:{type:['string','null']},evidence:{type:'object'}},false);
schema('report',object(['schema_version','skill_version','reviewed_at','scope','activation','deployment_identity','inventory','execution_graph','official_skills','rules','findings','tests','native_controls','coverage','usage_assessment','approvals','incomplete','tool_errors','overall_status','official_best_practices_status','cost_safety_status','predeploy_gate_status','deployment_gate_coverage','guarantees','review_identity'],{
 schema_version:{const:'1.0'},skill_version:string,reviewed_at:string,scope:{type:'object'},activation:{type:'object'},deployment_identity:{$ref:'deployment-identity.schema.json'},inventory:{type:'object'},execution_graph:{type:'object'},
 official_skills:{type:'array',minItems:3,items:object(['name','required','applies','reason','upstream','revision','resolved_path','content_digest','loaded_references','load_status','review_status','findings','evidence'],{name:string,required:{type:'boolean'},applies:{type:'boolean'},reason:string,upstream:{type:['string','null']},revision:{type:['string','null']},resolved_path:{type:['string','null']},content_digest:nullableSha,loaded_references:{type:'array'},load_status:string,review_status:string,findings:{type:'array'},evidence:{type:'array'}},false)},
 rules:{type:'array',minItems:12,maxItems:12,items:object(['rule_id','status','evidence','findings','gaps','implementation'],{rule_id:ruleId,status:{enum:['pass','finding','not_applicable','unknown','not_run']},evidence:{type:'array'},findings:{type:'array'},gaps:{type:'array'},implementation:{type:'object'}},false)},
 findings:{type:'array',items:finding},tests:{type:'array'},native_controls:{type:'array'},coverage:{type:'object'},usage_assessment:{type:'object'},approvals:{type:'array'},incomplete:{type:'array',items:string},tool_errors:{type:'array',items:string},review_identity:{type:['object','null']},
 overall_status:status,official_best_practices_status:status,cost_safety_status:status,predeploy_gate_status:{enum:['ALLOW','ALLOW_WITH_APPROVAL','DENY']},deployment_gate_coverage:{enum:['integrated_paths','partial']},guarantees:object(['hard_monthly_cap','production_isolation_performed','cloud_writes'],{hard_monthly_cap:{const:false},production_isolation_performed:{const:false},cloud_writes:{const:0}})
}));
schema('semantic-review',object(['schema_version','input_digest','reviewer','model','invocation','reviewed_at','rules','official_skills','tests','findings'],{
 schema_version:{const:'1.0'},input_digest:sha,reviewer:string,model:string,invocation:string,reviewed_at:string,
 rules:{type:'array',minItems:12,maxItems:12,items:object(['rule_id','status','reason','evidence'],{rule_id:ruleId,status:{enum:['pass','finding','not_applicable','unknown']},reason:string,evidence:{type:'array',minItems:1,items:location}})},
 official_skills:{type:'array',items:object(['name','status','reviewed_files','reason','evidence'],{name:string,status:{enum:['reviewed','unknown']},reviewed_files:{type:'array',items:object(['path','sha256'],{path:string,sha256:sha})},reason:string,evidence:{type:'array',minItems:1,items:location}})},
 tests:{type:'array',items:{...object(['id','status','input_digest','command','runner_digest','duration_ms','metrics'],{id:string,status:{enum:['passed','failed','unsupported','not_run']},input_digest:sha,command:{anyOf:[{type:'array',minItems:1,items:string},{type:'null'}]},runner_digest:nullableSha,duration_ms:{type:['number','null'],minimum:0},metrics:{type:'object'}}),allOf:[{if:{properties:{status:{enum:['passed','failed']}}},then:{properties:{command:{type:'array',minItems:1,items:string},runner_digest:sha,duration_ms:{type:'number',minimum:0}}}}]}},findings:{type:'array',items:finding},
 usage_assessment:object(['classification','scope','vector','assumptions','enforced_limits','evidence','excluded','usd_estimate'],{classification:{enum:['bounded_under_assumptions','unknown','unbounded_path']},scope:string,vector:object(dimensions,Object.fromEntries(dimensions.map(d=>[d,{type:['integer','null'],minimum:0}]))),assumptions:{type:'array',items:string},enforced_limits:{type:'array',items:object(['dimension','limit','scope','location'],{dimension:{enum:dimensions},limit:{type:'integer',minimum:0},scope:string,location})},evidence:{type:'array',minItems:1,items:location},excluded:{type:'array',items:string},usd_estimate:{const:null}})
}));
schema('trust',object(['schema_version','keys','official_skills_lock_digest','policy_digest','tool_digest','max_age_hours'],{
 schema_version:{const:'1.0'},keys:{type:'array',minItems:1,items:object(['id','public_key','roles','origins'],{id:string,public_key:string,roles:{type:'array',items:{enum:['review','approval']}},origins:{type:'array',minItems:1,items:string}})},official_skills_lock_digest:sha,policy_digest:sha,tool_digest:sha,max_age_hours:{type:'integer',minimum:1,maximum:168}
}));
schema('approval',object(['schema_version','input_digest','finding_ids','approver','reason','scope','expires_at','compensating_controls','evidence'],{
 schema_version:{const:'1.0'},input_digest:sha,finding_ids:{type:'array',minItems:1,uniqueItems:true,items:string},approver:string,reason:string,scope:string,expires_at:string,compensating_controls:{type:'array',minItems:1,items:string},evidence:{type:'array',minItems:1,items:string}
}));
